# Classification for SVHN dataset
model = "svhn-mixed" 
network_type = "classification"
model_profile_path = "models/svhn/svhn_mixed/classification_mixed_gr.pickle" # Change model directory in path as well.
centroids_save_path = "saved_parameters/init_centroids/svhn_mixed.pickle" # Read the centroids and use it during fuzzing. -> Store centroids first.
input_channels = 3
input_width = 32
input_height = 32 

# Dataset attributes
data = "svhn"
use_enriched_gt = "enriched"  # enriched, visible, all
data_path = "/data/vivek/current_datasets/svhn_dataset"
mode = 'test' # Only used to select split during fuzzing. Doesn't matter for centroids calculations.
num_classes = 10
num_workers = 2

# Mean and Std of Images for datasets
norm_mean_svhn = [0.43298, 0.44213, 0.47640]
norm_std_svhn = [0.19064, 0.19359, 0.19211]

pretrained_backbone = true

# for fuzzying
normalize_data = false # TO DO: prob while true.. bt we use normalised data...
batch_size = 16
num_mutants = 20
max_iterations = 15000
random = 0
seed_selection = "equal_samples" # prob
fuzz_criteria = "nbc" # nc, kmnc, nbc, lscd
fuzz_entire_test_set = false
init_seed_selection = "true_classified" # 'true_classified' & 'high_prob'

mutation_criteria = "transformations"
random_severity = false # false: constant severity level, true: random severity level

[detection_model]
	model = 'svhn-mixed'
	dataset = 'svhn'
	image_set = 'svhn'
